name = "clover"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_URL = "https://clover.azhr.workers.dev"
WA_NUMBER = "6281234567890"

[[d1_databases]]
binding = "DB"
database_name = "clover-db"
database_id = "c19b5005-10aa-4084-a168-2a165f935f4e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "clover-images"
